FROM python:3.13-slim as dev

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV VIRTUAL_ENV=/app/.venv
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

WORKDIR /app

RUN pip install --no-cache-dir --upgrade pip uv
RUN python -m venv $VIRTUAL_ENV

COPY uv.lock pyproject.toml ./

RUN uv sync

COPY . .

EXPOSE 8000

# The fix is to add 'uvicorn' and 'app.main:app' right after 'uv run'
CMD ["uv", "run", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]