[project]
name = "tarasov-auth"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.115.12",
    "pytest>=8.4.0",
    "ruff>=0.11.13",
]
